### ISSUE TITLE
Erro tratando chamada sem mTLS

### ISSUE THREAD

**Issue by fams** [fams/tlsjwt-gw#2]
Chamado sem certificado gerando erros no extauth
`
xtauth_1            | goroutine 34 [running]:
extauth_1            | main.(*ClientcertHeaderParts).GetCn(0xc00032a700, 0x5, 0xef0a40, 0x18, 0xc000557af8)
extauth_1            |  /build/cmd/tlsjwtgw/authorizationserver.go:98 +0x231
extauth_1            | main.(*AuthorizationServer).Check(0xc00032a500, 0x10c8cc0, 0xc0002b4bd0, 0xc0002b4c00, 0xc00032a500, 0xc0002b4bd0, 0xc00$
0e8ba8)
extauth_1            |  /build/cmd/tlsjwtgw/authorizationserver.go:237 +0x318
extauth_1            | github.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler(0xdda3c0, 0xc00032a500, 0x10c8$c0, 0xc0002b4bd0, 0xc00026e280, 0x0, 0x10c8cc0, 0xc0002b4bd0, 0xc0003ce900, 0x2cc)
extauth_1            |  /go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/service/auth/v2/external_auth.pb.go:471 +0x23e
extauth_1            | google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001080, 0x10d1900, 0xc00020a780, 0xc00023a500, 0xc0002b47b0, 0x17$e4e0, 0x0, 0x0, 0x0)
extauth_1            |  /go/pkg/mod/google.golang.org/grpc@v1.21.0/server.go:998 +0x470
extauth_1            | google.golang.org/grpc.(*Server).handleStream(0xc000001080, 0x10d1900, 0xc00020a780, 0xc00023a500, 0x0)
extauth_1            |  /go/pkg/mod/google.golang.org/grpc@v1.21.0/server.go:1278 +0xda6
extauth_1            | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003287e0, 0xc000001080, 0x10d1900, 0xc00020a780, 0xc00023a500)
extauth_1            |  /go/pkg/mod/google.golang.org/grpc@v1.21.0/server.go:717 +0x9f
extauth_1            | created by google.golang.org/grpc.(*Server).serveStreams.func1
extauth_1            |  /go/pkg/mod/google.golang.org/grpc@v1.21.0/server.go:715 +0xa1
`

**Comment by fams** [comment]
Resolvido com commits bd6ab687a8f0fef50e0f8498096f5f89da747d8e
e 7f65da90d575c61a8bf4a0a86fb19b19a305e069
